/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfac;

import DAO.AdminDao;
import DAO.ClientDao;
import Entities.Client;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferchichi
 */
public class ValiderClient extends javax.swing.JFrame {

    public void remplir(){
  List<Client> clients=new ArrayList<Client>();
    AdminDao agD=new AdminDao();
    
       
            clients=agD.valider();
       
    Object [][]data={};
    Object [] name={"nom","prenom","mail","date_naissance","sexe","etat","comportement","cin"};
    
    data=new Object[clients.size()][8];
    int indice=0;
    for(Client a:clients){
        data[indice][0]=a.getNom();
        data[indice][1]=a.getPrenom();
        data[indice][2]=a.getMail();
        data[indice][3]=a.getDate_naissance();
        data[indice][4]=a.getSexe();
        data[indice][5]=a.getetat();
        data[indice][6]=a.getComportement();
        data[indice][7]=a.getCin();
        
        indice++;
}
    DefaultTableModel m=new DefaultTableModel(data,name);
    jTable2.setModel(m);   
}
    /**
     * Creates new form ValiderClient
     */
    public ValiderClient() {
        
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Afficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(Afficher)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Afficher)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        
        List<Client> clients=new ArrayList<Client>();
    AdminDao agD=new AdminDao();
    
       
            clients=agD.valider();
       
    Object [][]data={};
    Object [] name={"nom","prenom","mail","date_naissance","sexe","etat","comportement","cin"};
    
    data=new Object[clients.size()][8];
    int indice=0;
    for(Client a:clients){
        data[indice][0]=a.getNom();
        System.out.println( data[indice][0] );
        data[indice][1]=a.getPrenom();
        System.out.println( data[indice][1] );
        data[indice][2]=a.getMail();
        System.out.println( data[indice][2] );
        data[indice][3]=a.getDate_naissance();
        System.out.println( data[indice][3] );
        data[indice][4]=a.getSexe();
        System.out.println( data[indice][4] );
        data[indice][5]=a.getetat();
        System.out.println(""+ data[indice][5] );
        data[indice][6]=a.getComportement();
        System.out.println(""+ data[indice][6] );
        data[indice][7]=a.getCin();
        System.out.println( data[indice][7] );
        
        
        
        indice++;
}
    
    
    DefaultTableModel m=new DefaultTableModel(data,name);
    jTable2.setModel(m);

    }//GEN-LAST:event_AfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValiderClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValiderClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValiderClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValiderClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValiderClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
